name: main

on:
  workflow_dispatch:

  push:
    branches: [main, develop]

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: ['**']

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment
        uses: monterail/github-actions/setup-js@main
